### ISSUE TITLE
Is it possible to get the inner worker? 

### ISSUE THREAD

**Issue by Swoorup** [mathe42/vite-plugin-comlink#100]
Using plain old workers, I currently have a channel to post back to the parent a message from worker for eg:

```typescript
updateInstructions(instructions: InstructionContainer) {
    self.postMessage({
      type: "updateInstructions",
      data: { chartId: this.chartId, instructions },
    });
  }
```

is it possible to get the worker instance so `onmessage` can be listened to for events from the worker? These are not necessarily return types.

**Comment by mathe42** [comment]
You could have this in your Worker:

```ts
let _cb = () => {}
export setUpdateHandler(cb: (param1: myType) => Promise<number>) {
  _cb = cb
}
```

And call that from the main thread with 

```ts
import {proxy} from 'comlink'
comlinkWorkerInstance.setUpdateHandler(proxy((param1) => {
  // do something
  return 42
}))
```

**Comment by Swoorup** [comment]
Wow, yeah, thats better. Thanks from the prompt response 😛
