### ISSUE TITLE
ComlinkWorker is not defined

### ISSUE THREAD

**Issue by scott-cornwell** [mathe42/vite-plugin-comlink#101]
So I'm using ComlinkWorker in one place and it works fine, but if I try to use it in another place it is undefined. It's part of the same project and I'm not really sure what the difference is. It's not from inside a worker or anything. The one that works is initialized when the app starts whereas the one that doesn't work is created in response to me clicking something in my UI.

Wish I could just import it so I don't have to rely on it being magically available.

**Comment by mathe42** [comment]
ComlinkWorker only exists at compile time not at runtime! So ComlinkWorker gets transformed and there is no ComlinkWorker Class.

Therefore you can only have `new ComlinkWorker(new URL(...), {option})` not for example a `console.log`.

If this information doesn't help you please provide some code so I can debug it.

**Comment by scott-cornwell** [comment]
Hmm well I really need it to work at runtime I guess. Is there a way to work around this by just using straight comlink and get similar behavior?

**Comment by mathe42** [comment]
Yes you can use "plain" comlink. And create the worker yourself...

**Comment by scott-cornwell** [comment]
I've tried that but I'm not able to get it to work from their examples. It would be really great if vite-plugin-comlink supported this. Also even where it works I'm not able to do things like create a base worker class. Oh well, thanks for your quick response.

**Comment by mathe42** [comment]
If you share your code / problem I might be able to help / provide a workaround. But the general problem is out of scope of this plugin...

**Comment by scott-cornwell** [comment]
Well it's 1000s of lines of code. But I'm just trying to create a worker that I can use in a similar way to ComlinkWorker. I created a class something like this:
```
import * as Comlink from 'comlink'
class TestWorker {
  constructor() {
  }

  testFunction() {
  }
}

Comlink.expose(TestWorker);
```

I try to create it from main thread like this:
```
      const worker = Comlink.wrap(new Worker(new URL('./TestWorker.js', import.meta.url), {
        type: 'module',
      }))
     worker.testFunction()
```

It errors with `cannot read properties of undefined (reading 'testFunction')`, so exposing the functions on my worker does not work, even though it creates a proxy object for the worker.

**Comment by mathe42** [comment]
You have to create a instance of your class:

```
Comlink.expose(TestWorker);
```
has to be
```
Comlink.expose(new TestWorker());
```

**Comment by scott-cornwell** [comment]
I finally got it working, I needed to do it a little different because I'm creating multiple instances. If I keep my TestWorker like I had it and create the instance like this it works:
```
      const TestWorker = Comlink.wrap(new Worker(new URL('./TestWorker.js', import.meta.url), {
        type: 'module',
      }))

      const worker = await new TestWorker()
```

Thanks for your help!

**Comment by mathe42** [comment]
This should also work with this Plugin:

```
const TestWorker = new ComlinkWorker(new URL('./TestWorker.js', import.meta.url), {
        type: 'module',
})

const worker = await new TestWorker()
```

**Comment by scott-cornwell** [comment]
Hmm yeah I don't know why, but that doesn't work for me. `rawValue is not a constructor`.

**Comment by mathe42** [comment]
strange... good that you found a workaround.

**Comment by albertreed** [comment]
@scott-cornwell I'm doing what sounds like the exact same thing as you and can't manage to get it working. new TestWorker() is returning a promise but that promise never resolves.

Was there some other voodoo you had to do? I've removed vite-plugin-comlink just to see if that unstuck it but no luck.

**Comment by scott-cornwell** [comment]
@albertreed I've changed the way I'm doing it a little bit, try this:
```js
import * as Comlink;
class BaseWorker {
  workers = []
  constructor() {
  }
  connectWorker = msg => {
     const { port, workerId } = msg
     const wrappedPort = Comlink.wrap(port)
     Comlink.expose(this, port)
     this.workers[workerId] = wrappedPort
  }

  doSomething = msg => {
    // you can call a connected worker like this:
   // note: this is a simplified example, make sure to use the right id that is actually connected
    this.workers[1].doSomething() 
  }
}
export { BaseWorker }
```

```js
import * as Comlink;
export const getWorkerType = path => {
  const urlObject = new URL(path, import.meta.url)
  return fetch(urlObject.pathname).then(result => {
    if (result.status !== 200) {
      throw new Error(`worker path not found ${urlObject.pathname}`)
    } else {
      const worker = new Worker(urlObject, { type: 'module' })
      const WorkerType = Comlink.wrap(worker)
      return WorkerType
    }
  }).catch(e => {
    console.error(e)
  })
}

const initWorkers = async () => {
  const BaseWorker = await getWorkerType('./BaseWorker.js')
  const worker1 = await new BaseWorker() // it's important to use await here too
  const worker2 = await new BaseWorker()
  const channel = new MessageChannel()
  
  worker1.connectWorker({ id: 1, port: channel.port1 })
  worker2.connectWorker({ id: 2, port: channel.port2 })
  worker1.doSomething()
  worker2.doSomething()
}

initWorkers()
```

You can extend BaseWorker and use getWorkerType on that to make specific types of workers, and make multiple of them at runtime as well. This shows how to connect any 2 workers to each other. If you want to connect a worker to the main thread the way I do it is create an object or class instance on the main thread for each connection and Comlink.expose that with one port and the other sent to a worker. It seems you need a different object for each connection though, it does not working doing expose on the same object multiple times to connect to different workers. Hope this helps!

**Comment by albertreed** [comment]
Got it, thanks a ton for the detail. For future readers who are also wanting to dynamically create the workers, my fix ended up being to import the worker typescript file as like this (my worker is called "SimWorker"):

`import SimWorker from "./SimWorker?worker";`

Wrap it like this

`Comlink.wrap(new SimWorker());`

And then do this to construct it with whatever params you want:

`await new WrappedSimWorker(<parameters>);`

The class is exported like this:
`export class SimWorker {`

and at the end of the file that defines the class I do:

`Comlink.expose(SimWorker);`
