### ISSUE TITLE
ComlinkWorker not being transformed

### ISSUE THREAD

**Issue by lancetipton** [mathe42/vite-plugin-comlink#107]
First off thanks for the repo, and the work put into it. **It is appreciated.**

## Context

* I've been using this plugin for a while, and recently updated to the latest version of vite.
  * I was originally using the `@vitejs/plugin-react` plugin alongside this one.
  * Unfortunately I was running into issues with vite, and I tried upgrading vite to a new version.
  * Where I ran into further issues, reported [here](https://github.com/vitejs/vite/issues/13030#issuecomment-1527500519)

* In an effort to resolve the above issues, I switched over to the `@vitejs/plugin-react-swc` plugin.
  * Using this plugin does seem to fix the issues, but seems to cause problems with this plugin.
  * It looks like the plugin never runs, so the file that creates the worker throws an error of `ComlinkWorker is not defined`
  * This was working without issue before I updated vite, then switched to the `@vitejs/plugin-react-swc` plugin

* To be honest I'm not sure if it's related to this plugin or something else with my configuration
  * It's a little bit non-standard which would make it difficult to recreate a demo of, but I can try if it's really needed
  * My hope is I'm missing something simple, like a config option that will resolve the issue.

* Checking the current issues, I seen similar issues reported before
  * They seem to be unrelated to the issue I currently facing
  * They are also closed, and so I figured I just open a new issue instead

### Package.json
![image](https://user-images.githubusercontent.com/8345382/236697919-81c5de83-e089-46e3-9789-50a6368fb764.png)

### Create worker file
![image](https://user-images.githubusercontent.com/8345382/236697968-3168c8e6-4890-4413-89fb-50fd4682b061.png)

### Chrome Inspector Error
![image](https://user-images.githubusercontent.com/8345382/236698769-afc4ca7e-db20-429f-adc0-9fe035eaa21a.png)

### Vite Config
![image](https://user-images.githubusercontent.com/8345382/236698931-066d0d17-9e6c-4af1-b9ac-22ca51d6cbeb.png)

## Comments
* I realize this might be not related to this plugin, as it seems the plugin is not even being executed, but I figured I start here first.
* Any direction you can provide would be appreciated.

Thanks

**Comment by mathe42** [comment]
Thinks you could try: 
1. Switch order of plugins (maybe react has to be before comlink not sure; tsconfigpath at start etc.)
2. Remove some plugins so you can check if it changes something
3. Use vite-plugin-inspect to see transforms
4. add a args object to ComlinkWorker

For more help it would be great to have a minimal (or as minimal you can make it) example that doesn't work.

**Comment by lancetipton** [comment]
Thanks for the fast response. I'll try the things you mentioned. If they don't work, I'll try putting together an example repo.
Hopefully I can knock something loose.

**Comment by lancetipton** [comment]
Switching the order looks to have fixed it. For my configuration at least, the `react()` plugin from `@vitejs/plugin-react-swc` had to come first. After moving it to the top, everything is now working as expected. 

![image](https://user-images.githubusercontent.com/8345382/236699861-4928d6fd-a773-4e6e-abe7-6dea50e5e59e.png)

Figured, I'd add an image incase someone else comes across this.

Thanks again for the help.
