### ISSUE TITLE
Vite.config ts issue, Type 'Plugin_2[][]' is not assignable to type '() => PluginOption[]'

### ISSUE THREAD

**Issue by artem-tarasenko** [mathe42/vite-plugin-comlink#130]
Hi,

I have an issue setting up this plugin with comlink.

Following the docs, I've added the plugin to the `plugins` array and to `worker.plugins` but got an error about incompatible types.

```
No overload matches this call.
  The last overload gave the following error.
    Type 'Plugin_2[][]' is not assignable to type '() => PluginOption[]'.
      Type 'Plugin_2[][]' provides no match for the signature '(): PluginOption[]'.ts(2769)
reporters-1evA5lom.d.ts(1789, 18): The last overload is declared here.
```

```
"vite": "^4.5.2",
"vite-plugin-comlink": "^4.0.2",
"typescript": "^4.9.3",
```

Would appreciate any hints on what's going on.

**Comment by mathe42** [comment]
Please provide a reproduction for this = at least your full vite config

**Comment by artem-tarasenko** [comment]
Here you go [Stackblitz Vite Starter](https://stackblitz.com/edit/vitejs-vite-atyxpy?file=vite.config.ts)

**Comment by mathe42** [comment]
Use
```ts
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { comlink } from 'vite-plugin-comlink';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [comlink(), react()],
  worker: {
    plugins: () => [comlink()],
  },
});
```

As your config this is a change in vite 5 I didn't see...

**Comment by artem-tarasenko** [comment]
Oh, right... The double array in the type confused me but it unfolds...  Thanks, Sebastian!
