### ISSUE TITLE
Use Github Release feature to improve change documentation

### ISSUE THREAD

**Issue by charlieforward9** [mathe42/vite-plugin-comlink#131]
Hello! Thank you for providing this functionality for the open source community!

I was going through my Dependa-bot PRs and updating my dependancies. One thing I tend to do as I wait for the PRs to rebase between merges is check the changelog for each of the dependencies.

This helps me understand what has changed in the tools I use, to understand how they work, if I need to change anything, and gets me a little closer to the logic I depend on. 

Usually the best spot for that is in a CHANGELOG file, but if you dont want to manually maintain something, I recommend using the Github Release feature, which does a great job auto-documenting the CHANGELOG based on your PR titles. 

I hope you consider this as you continue developing this incredibly helpful plugin.

**Comment by mathe42** [comment]
Sure.
