### ISSUE TITLE
How to Terminate Web Worker if Task is Completed.

### ISSUE THREAD

**Issue by janaanimator** [mathe42/vite-plugin-comlink#132]
1) How do I terminate the Web Worker when task is completed ?

2) This code is also not helping me.

```
import {releaseProxy} from 'comlink'

comlink[releaseProxy]()
```

3) In browser I can see the Web worker running in **Sources Tab**.

4) In documentation also there is no proper way to Close and Terminate.

**Please me give proper way to close and Terminate Web worker once Task is completed.**

5) Thanks for your Plugin @mathe42  its help me reduce the development time.

6) Kindly help me ASAP.

**Comment by mathe42** [comment]
If you Set
myComlinkeworker = null
or it gets out of scope the GC should GC the worker and terminate it.

Or you call self.close() inside the worker.

**Comment by janaanimator** [comment]
Thank you @mathe42
``
self.close();
``
This code Solved my Issue. 
Once again Thankyou.

**Comment by tennox** [comment]
For anyone else landing here, check out https://github.com/mathe42/vite-plugin-comlink/pull/138
