### ISSUE TITLE
Does library work at runtime?

### ISSUE THREAD

**Issue by vildantursic** [mathe42/vite-plugin-comlink#139]
I've managed to make it work after build, works great, but at runtime I constantly get `ReferenceError: ComlinkWorker is not defined` am I doing something work or it only works after app is built?
Thanx

**Comment by mathe42** [comment]
Yes it should work.

Please search for issues with your error message you find for example https://github.com/mathe42/vite-plugin-comlink/issues/107 that should help. 

If this doesn't help please open a new issue with a code reproduction.
