### ISSUE TITLE
import "path/posix" doesn't work on Node.js 14

### ISSUE THREAD

**Issue by peter50216** [mathe42/vite-plugin-comlink#14]
The import alias is added in Node.js [15.3.0](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V15.md#2020-11-24-version-1530-current-codebytere).

It might be better to import "path" instead which should work on older version of node.

**Comment by peter50216** [comment]
Wow thanks for the instant fix!

**Comment by mathe42** [comment]
Fixed in 2.0.1

**Comment by peter50216** [comment]
Looks like the current code still import from `"path/posix"`

**Comment by mathe42** [comment]
Ups :D

Is fixed in 2.0.2 will look at vite-plugin-worker there should be the same problem
