### ISSUE TITLE
Uncaught (in promise) ReferenceError: ___wrap is not defined

### ISSUE THREAD

**Issue by smilingovo** [mathe42/vite-plugin-comlink#142]
**Describe the bug**
When I use the pnpm workspace in a vite project and use the setup function of vue3, according to the case you gave, the result is an error

**Screenshots**
![image](https://github.com/mathe42/vite-plugin-comlink/assets/64189989/ee69e607-38aa-4a34-a736-7d829399e9c7)

**Desktop (please complete the following information):**
 - Browser chrome

**Comment by mathe42** [comment]
Please provide a minimal reproduction.

**Comment by mathe42** [comment]
Closing as no reproduction is provided.
