### ISSUE TITLE
Question: Can we have a new version with the .d.ts generation fix?

### ISSUE THREAD

**Issue by peter50216** [mathe42/vite-plugin-comlink#15]
Currently 2.0.0-beta.1 will add a new line to the generated .d.ts on each invocation of vite. Looks like this is already been fixed by [the commit](https://github.com/mathe42/vite-plugin-comlink/commit/ba793d747fc56b6eeabe14e105e7c2ef02f7f2d4), but is not included in any published package to npm yet.

**Comment by mathe42** [comment]
Yes there is a bug. Will fix that.

**Comment by mathe42** [comment]
Fixed in 2.0.1
