### ISSUE TITLE
Cannot make it to work with SharedWorker

### ISSUE THREAD

**Issue by pvcnt** [mathe42/vite-plugin-comlink#157]
**Describe the bug**
I am trying to use this plugin with a SharedWorker, and hit the following error:
```
TypeError: ep.postMessage is not a function
    requestResponseMessage comlink.ts:613
    requestResponseMessage comlink.ts:601
    apply comlink.ts:504
```

I did some debugging and `ep` is an instance of `SharedWorker`, which indeed does not have a `postMessage` method (`ep.port` has though).

**To Reproduce**
I am using the following snippet:
```typescript
const worker = new ComlinkSharedWorker<typeof import("./worker")>(
    new URL("./worker", import.meta.url), {type: "module"}
);
await worker.refresh();
```

**Expected behavior**
It should work.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version [e.g. 22]: 127.0.2

**Comment by mathe42** [comment]
This is a bug created with my 5.0 refactoring.
