### ISSUE TITLE
Possibility to use Query suffix

### ISSUE THREAD

**Issue by throrin19** [mathe42/vite-plugin-comlink#167]
**Is your feature request related to a problem? Please describe.**
Add the possibility to load directly our code as a ComLink worker without this part : 

```js
new ComlinkWorker(new URL("./worker.js", import.meta.url), {
  /* normal Worker options*/
});
```

**Describe the solution you'd like**
Add the possibility to pass by Query suffix on import our worker to do that dirrectly like : 

```js
import MyWorker from './worker.js?comlinkworker';
```

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered: none other :( 

**Additional context**
I juste push this request before found possibility to load workers in vite : https://vite.dev/guide/features.html#web-workers

**Comment by henryStelle** [comment]
I was also just thinking it would be great if the Vite query import structure was supported by this plugin!

**Comment by mathe42** [comment]
This is an intentinal missing thing. The first version of this plugin used an import syntax. As Vite intodruced the differnet syntax it got addopted as it solved complicated stuff. (This plugin had to reinvent some Vite features to work properly)

Also TS support was tricky. If I implemented that now I would not add TS support and with that the hole thing is pointless. Just wrap the Worker in comlink on your own...

Also Vite-Docs state that:

"Compared to the worker suffixes, this syntax leans closer to the standards and is the recommended way to create workers."

When the new syntax got launcht it looked to me that the "old" syntax will be deprected and removed some day.

**Comment by mathe42** [comment]
closing as won't change
