### ISSUE TITLE
Can't modify worker URL in runtime

### ISSUE THREAD

**Issue by lauri865** [mathe42/vite-plugin-comlink#172]
**Describe the bug**
Our bundle is served from a CDN, but cross-origin use of SharedWorkers is not permitted under any condition, hence we need to serve the worker from origin.

**To Reproduce**
Let's leave CDN aside for now. This works:
```typescript
const instance = new ComlinkSharedWorker(
  new URL(
    "@/lib/supabase.sharedworker.js",
    import.meta.url,
  )
);
```

This doesn't work – results in `PresenceIndicator.tsx:21 Uncaught ReferenceError: ComlinkSharedWorker is not defined`:
```typescript
const instance = new ComlinkSharedWorker(
  new URL(
    "@/lib/supabase.sharedworker.js",
   "https://site.local/src/components/Component.tsx?t=1731254023959",
  )
);
```

Mind you that I have just statically added the value of `import.meta.url`, but even that doesn't work. Let alone dynamic values.

**Expected behavior**
Ability to specify the worker URL during runtime, to match the origin.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS 15
 - Browser: Chrome
 - Version: 130.0.6723.92
 - Vite 5

**Comment by lauri865** [comment]
The culprit seems to be this line: https://github.com/mathe42/vite-plugin-comlink/blob/ce8f5a903ad120d54ec2116beec46b87b920a844/src/index.ts#L65-L66

Which limits the syntax very narrowly.

Is there a reason why the instance wrapping has to be done on build-time? The worker itself I understand, but the instance – less so, especially given the limitations of SharedWorkers.

**Comment by lauri865** [comment]
On a second thought, I removed the plugin altogether. Literally just a few more lines of code without any "magic" that's difficult to inspect. Not sure what the plugin is supposed to solve (genuine question, I don't mean to offend anyone), but it caused use many hours of figuring things out. Just wished it was a tutorial/blog post instead, and we could just copy the code.

I'd understand if it somehow inlined types or added any other benefits, but maybe I'm just missing it. At the very least it could be an imported function instead of a new function that is injected into the global scope.

**Comment by mathe42** [comment]
Yes the Plugin is not for all Comlink use cases.

This Plugin is if you want to use Comlink in your vite-Project and build the Worker together with the rest of the project.

Even then you don't have to use this Plugin but this Plugin removes some overhead that you might have with typings and forces you to use a specific syntax.


The idea was basicly to reuse the vite syntax and just replace Worker -> ComlinkWorker.

**Comment by lauri865** [comment]
But vite already builds workers together with the rest of the project. Typings have the same overhead (I need to manually provide them to the generic either way), minus the fact that I can directly infer the types from Comlink wrap. Maybe the worker support was worse in earlier Vite versions, but today, I don't see the value quite frankly, even if our use case did fit in the scope.

This would be an implementation for the core user of this plugin:

main.ts
```typescript
import worker from "./worker?worker";
import * as Comlink from "comlink";

const rpc = Comlink.wrap<import("@/lib/worker").Api>(worker);
await rpc.add(1, 2);
```

worker.ts
```
import * as Comlink from "comlink";

const api = {
    add: (a: number, b: number) => a + b,
};

Comlink.expose(api);
export type Api = typeof api;
```

Et voila, now you can probably upgrade Vite as soon as it's available, as well as Comlink, if they come out with a new major, and you need some new functionality. Took me more time to wrap my head around the docs of a new plugin than to write this.
