### ISSUE TITLE
Testing with plugin

### ISSUE THREAD

**Issue by hmt** [mathe42/vite-plugin-comlink#25]
This isprobably out of scope for this project but I'm trying to use uvu with my project to test part of the vite app. Running just uvu on the ts code doesn't work because the imported worker doesn't resolve (due to the import syntax `Error: Cannot find module 'comlink:./WorkerKatalog'`). Is there a way to make this plugin work without vite or inside and outside of a vite context?

**Comment by mathe42** [comment]
Have a look at rollup-plugin-comlink by surma. Might what you need.  but this plugin depends deeply on vite internals so no way to use it outside.

**Comment by hmt** [comment]
ok, thank you. I switched to plain Comlink and used the other rollup worker loader plugin to include it in my builds. Not as comfortable as yours but does the job as well.
