### ISSUE TITLE
Conflict with vite legacy plugin

### ISSUE THREAD

**Issue by sep2** [mathe42/vite-plugin-comlink#34]
Please see the repro here: https://github.com/sep2/conflict-with-legacy-plugin

**Comment by mathe42** [comment]
Could reproduce. Will need some time to look into it. Might be a problem with the legacy-plugin. Did you try the "normal" vite workers (with `./file?worker`) with the legacy plugin?

**Comment by sep2** [comment]
Haven't try that yet, will do later

**Comment by sep2** [comment]
There is no problem with the `./file?worker` method, the worker file are only wrapped in an IIFE, no other code being injected.
```js
!function(e) {
    "use strict";
    e.add = async function(e, n) {
        const t = await async function(e) {
            return Promise.resolve(e)
        }(e);
        return t + n
    }
    ,
    Object.defineProperty(e, "__esModule", {
        value: !0
    })
}({});
```

**Comment by mathe42** [comment]
After some digging into it I think there is no way to change this on my side. Only thing might be to use this https://github.com/mathe42/vite-plugin-bundle#specify-used-plugins with context name worker to disable some plugins.
Or I could add a special check so this line gets removed again - but both is not optimal.

**Comment by sep2** [comment]
@mathe42 Could you elaborate a bit further on how to work around this issue?

**Comment by mathe42** [comment]
I think I fixed it!

Make shure to use vite-plugin-bundle@1.1.0 not shure if I broke anything. I can not test it on IE.

**Comment by sep2** [comment]
There is one 'e' character remain in the output worker: 

`e!function(){"use strict";va`

Which leads to `convert-data.worker.fa95352c.js:formatted:1 Uncaught SyntaxError: Unexpected token '!'`.

Maybe this [`startpos + 1`](https://github.com/mathe42/vite-plugin-bundle/blob/ab844b57c66515458af6b957fbcb170aba75e5bd/src/index.ts#L112) caused the problem.

**Comment by mathe42** [comment]
Shit. Forget to fix that there :D. Tested it by changeing the dist file :( - Use Version 1.1.1

**Comment by sep2** [comment]
Confirm fixed! Thank you very much!
