### ISSUE TITLE
Firefox support for vite-dev

### ISSUE THREAD

**Issue by vibaiher-qatium** [mathe42/vite-plugin-comlink#36]
Hi @mathe42!

Congratulations on this awesome plugin, it works really really nice.

We are migrating a CRA project to Vite, our app uses workers extensively and it would be nice to test them during development in other browsers different from Chrome. Do you know any workaround to enable support on Firefox when using the Vite dev mode?

We are very interested, so if you think we can contribute to this plugin by coding, please point us in a good direction.

**Comment by mathe42** [comment]
I will add an Option for that in the next day or so. Should be quite easy. Note that latest Version of Safari also works in Dev Mode.

Nur expect poor loading Times!

**Comment by mathe42** [comment]
No update required just use the (currently not documented) customConfigs option:


```ts
{
  plugins: [
    comlink({
      customConfigs: {
        "comlink:": "comlink@main:worker-iife:comlink@worker:",
      }
    })
  ]
}
```
This will tranform the workers to an iife and don't use module syntax.

Note that it is currently only FireFox not supporting module Workers. See

https://caniuse.com/mdn-api_worker_worker_ecmascript_modules

**Comment by vibaiher-qatium** [comment]
Thank you @mathe42!

Almost all the dev team uses Chromium, but sometimes we test new features over Firefox. We will probably just document the workaround so Firefox users can modify the config when required.

Thank you very much!
