### ISSUE TITLE
when use inline worker , lose comlink wrap 

### ISSUE THREAD

**Issue by cataben** [mathe42/vite-plugin-comlink#45]
I need an inline worker, import my worker like this:
```js
// use vite-plugin-worker  'worker-inline:'  and  vite-plugin-comlink  'comlink:./worker'

import myInlineWorker from 'worker-inline:comlink:./worker'
```

run `vite build` successfully , but in the bundle, It lose comlink wrap.
```js
// only vite-plugin-worker resolved

function workerWrapper() {
  return new Worker((window.URL || window.webkitURL).createObjectURL(new Blob([atob("KGZ1bmN0aW9uK.......")], { type: "text/javascript;charset=utf-8" })), { "type": "classic" });
}
```

[the link to vite-plugin-comlink source code ](https://github.com/mathe42/vite-plugin-comlink/blob/main/src/index.ts#:~:text=switch%20(schema)%20%7B-,case,-%22comlink%40main%3A%22%3A)

```js
 // I debug here,  it shows realFile  =  'worker:comlink@worker:/src/worker.ts?entry_file'

    case "comlink@main:":
        return `
          import { wrap } from 'comlink'
          import createWorker from ${JSON.stringify(realFile)}

          export default () => wrap(new createWorker())
        `;
```

Why comlink failed?   Did comlink be tree-shaked ?  

look forward to your kind reply~

**Comment by mathe42** [comment]
Use in config:

```ts
{
  plugins: [
comlink({
  customConfigs: {
    "comlink-inline:": "comlink@main:worker-inline:comlink@worker:",
}})
```

And use import api from 'comlink-inline:./path.js'

**Comment by mathe42** [comment]
That Option ist currently not documented but I will rewrite this Plugin for Vite >= 2.8 but have some Problems so this Option is unstable!

**Comment by Swoorup** [comment]
> Use in config:
> 
> ```ts
> {
>   plugins: [
> comlink({
>   customConfigs: {
>     "comlink-inline:": "comlink@main:worker-inline:comlink@worker:",
> }})
> ```
> 
> And use import api from 'comlink-inline:./path.js'

Is this still the preferred way?

**Comment by Swoorup** [comment]
Looks like this was removed.
