### ISSUE TITLE
Version 3

### ISSUE THREAD

**Issue by mathe42** [mathe42/vite-plugin-comlink#52]
I just released version 3. This is a complete rewrite using the new Worker and SharedWorker syntax.

Please update!

Migration-guide:
1. If you use vite-plugin-comlink with service-worker this will not work anymore so remove them please! If vite adds service-worker build support I will add it!
2. Remove `vite-plugin-worker` and `vite-plugin-bundle`
3. Update `vite` config.
4. Remove all options. Custom-config is no longer supported and tsfile is removed (how to use it with types see readme).
5. You can still run the "old" import syntax but that is deprecated and will be removed in version 4 (so you have some time to switch!!!)

The plugin will log some deprecation messages if you use syntax that will be removed.

With this release I stop maintaining vite-plugin-worker and vite-plugin-bundle as those where just workarounds for missing vite-features.

**Comment by vibaiher-qatium** [comment]
@mathe42 This new version is very promising.

We have tried it, and it works quite fine, but we detected that the source map generated is using a different hash value than the worker.js generated.

This is the config we are using:

```
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import svgr from "@svgr/rollup";
import envCompatible from "vite-plugin-env-compatible";
import comlink from "vite-plugin-comlink";
import {
  CUSTOM_ALIASES,
  PROBLEMATIC_LIBRARIES,
  POLYFILLS
} from "./config/aliases";

export default defineConfig({
  plugins: [
    react(),
    svgr({ svgo: false }),
    envCompatible({ prefix: "REACT_APP", mountedPath: "process.env" }),
    comlink()
  ],
  worker: {
    plugins: [
      comlink()
    ]
  },
  optimizeDeps: {
    include: ["comlink"]
  },
  server: {
    host: true,
    port: 3000
  },
  build: {
    outDir: "build",
    sourcemap: "hidden"
  },
  resolve: {
    alias: {
      ...CUSTOM_ALIASES,
      ...PROBLEMATIC_LIBRARIES,
      ...POLYFILLS
    }
  }
});
```

We are importing the Worker this way:

```
import * as Comlink from "comlink";

const worker = new ComlinkWorker(new URL("./worker", import.meta.url));
```

If this info is not enough I can try to reproduce it with a blank project.
