### ISSUE TITLE
vite: Could not resolve entry module

### ISSUE THREAD

**Issue by jim-fx** [mathe42/vite-plugin-comlink#53]
Hi @mathe42,

thank you for the cool plugin, it makes working with workers even more enjoyable.

I have encountered an issue with the plugin during vite's build stage, which causes the build process to fail.

```bash
> vite-comlink-repro@0.0.0 build /Projects/vite-comlink-repro
> tsc && vite build

vite v2.9.6 building for production...
✓ 0 modules transformed.
✓ 2 modules transformed.
[vite:worker-import-meta-url] Could not resolve entry module (src/____:com_link:./worker).
file: /Projects/vite-comlink-repro/src/main.ts
error during build:
Error: Could not resolve entry module (src/____:com_link:./worker).
    at error (/Projects/vite-comlink-repro/node_modules/.pnpm/rollup@2.71.1/node_modules/rollup/dist/shared/rollup.js:198:30)
    at ModuleLoader.loadEntryModule (/Projects/vite-comlink-repro/node_modules/.pnpm/rollup@2.71.1/node_modules/rollup/dist/shared/rollup.js:22491:20)
    at async Promise.all (index 0)
 ELIFECYCLE  Command failed with exit code 1.
```

I am not sure if it is necessary, but here is a super stripped down reproduction of the issue:

https://github.com/jim-fx/vite-comlink-repro

Thank You 👋

**Comment by mathe42** [comment]
Oh shit this is a doc mistake sorry use
```ts
import { comlink } from "vite-plugin-comlink"

export default {
  plugins: [comlink()],
  worker: {
    plugins: [
      comlink()
    ]
  }  
}
```

will update readme later... I will keep this open until I fix the readme.

**Comment by mathe42** [comment]
Thanks for the report. Didn't catch this... I think I should add testing but I have no idea how...

**Comment by jim-fx** [comment]
Awesome, thanks for the quick reply and solution :)
