### ISSUE TITLE
default export doesn't work. "TypeError: xxx is not a function"

### ISSUE THREAD

**Issue by colecrouter** [mathe42/vite-plugin-comlink#54]
First off, thank you for making this!

I noticed in the installation section, your `vite.config.js` reads:
```js
import comlink from 'vite-plugin-comlink'
```
In practice, I'm only able to get it to work with:
```js
import { comlink } from 'vite-plugin-comlink'
```
Is this the intended behaviour?

**Comment by mathe42** [comment]
Yes your  right will fix the code

**Comment by mathe42** [comment]
Released a fix as 3.0.1. Thanks for the report!

**Comment by mathe42** [comment]
Are you sure you are on the latest version?

**Comment by ivancuric** [comment]
`    "vite-plugin-comlink": "^3.0.2"`

**Comment by mathe42** [comment]
It works properly see https://github.com/mathe42/comlink-test please change to "3.0.2" and not "^3.0.2".

**Comment by ivancuric** [comment]
Here's my repro:
https://github.com/ivancuric/vite-workers/tree/repro-broken-comlink

```
failed to load config from /Users/ivan/Dev/vite-workers/vite.config.js
error when starting dev server:
TypeError: comlink is not a function
    at file:///Users/ivan/Dev/vite-workers/vite.config.js?t=1653404879713:4:13
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async loadConfigFromFile (/Users/ivan/Dev/vite-workers/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:61843:31)
    at async resolveConfig (/Users/ivan/Dev/vite-workers/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:61376:28)
    at async createServer (/Users/ivan/Dev/vite-workers/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:59783:20)
    at async CAC.<anonymous> (/Users/ivan/Dev/vite-workers/node_modules/vite/dist/node/cli.js:688:24)
    ```

**Comment by mathe42** [comment]
I have no idea why it works with my project and not yours. I published a new version 3.0.3 that didn't fix it. I will keep looking into it but not today.

**Comment by Mexican-Man** [comment]
Normally, you just have to change
```ts
export function
```
To
```ts
export default function
```
Right? I can't explain the local reproduction issue, though.

**Comment by ivancuric** [comment]
It's the `"type": "module"` in the project's package.json which breaks it. This instructs the project to use esm with node 16+

Seems that something is broken with the .mjs module.

```js
var src_default = comlink;
export {
  comlink,
  src_default as default
};
```

**Comment by mathe42** [comment]
It uses the normal .js file in both cases.

**Comment by ivancuric** [comment]
It does, but it should be using the .mjs I think.

I can't get it to load the mjs file.

**Comment by mathe42** [comment]
note that this might be a combination with vite problem as at vite startup the config file is compiled to JS (and I think the complete config is bundled to a single file internaly.) The output of that is interpreted as a commonjs (or with type=module a esm)-File.

**Comment by mathe42** [comment]
What is the reason you want to set `type: module` in a vite project. You could just change all `.js` extensions to `.mjs` where you have some code for node... the type field doesn't matter for vite-plugins and files vite processes.

**Comment by ivancuric** [comment]
I have it as I used to get errors otherwise — I think in other config tools like eslint, or typescript, but I can't be sure.

Could this be related to https://github.com/vitejs/vite/issues/6623?

I also noticed that when compiling in lib mode in Vite, they recommend using the following package.json:

```json
{
  "name": "my-lib",
  "files": ["dist"],
  "main": "./dist/my-lib.umd.js",
  "module": "./dist/my-lib.es.js",
  "exports": {
    ".": {
      "import": "./dist/my-lib.es.js",
      "require": "./dist/my-lib.umd.js"
    }
  }
}
```

Compared to yours it's missing the `exports` field.

**Comment by mathe42** [comment]
Might be. exports field doesn't change anything. Reproduction is still broken. I think the best solution is to avoid the default import. vite 3 will have some changes with esm files etc. so I would not touch it for now and wait for the 3.0 release.

**Comment by mathe42** [comment]
I know that vite 3 is out but I'm currently quite busy (I'm in my last year of University) so at least in the next 4-5 Weeks don't expect a fix. I didn't even had a look at vite 3 yet. (so also vite-plugin-comlink version 4 is pushed back). On npmjs I can see that a lot of persons only use an old version:

![image](https://user-images.githubusercontent.com/24830662/179609482-f8169a76-9bff-4b21-b06b-7a7798972a7e.png)

So there is no harm in waiting for v4 as it will have a number of breaking changes.

**Comment by mathe42** [comment]
This shoudn't be a problem anymore. If it is feel free to reopen...
