### ISSUE TITLE
sourcemaps have different hashes

### ISSUE THREAD

**Issue by mathe42** [mathe42/vite-plugin-comlink#59]
@mathe42 This new version is very promising.

We have tried it, and it works quite fine, but we detected that the source map generated is using a different hash value than the worker.js generated.

This is the config we are using:

```
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import svgr from "@svgr/rollup";
import envCompatible from "vite-plugin-env-compatible";
import comlink from "vite-plugin-comlink";
import {
  CUSTOM_ALIASES,
  PROBLEMATIC_LIBRARIES,
  POLYFILLS
} from "./config/aliases";

export default defineConfig({
  plugins: [
    react(),
    svgr({ svgo: false }),
    envCompatible({ prefix: "REACT_APP", mountedPath: "process.env" }),
    comlink()
  ],
  worker: {
    plugins: [
      comlink()
    ]
  },
  optimizeDeps: {
    include: ["comlink"]
  },
  server: {
    host: true,
    port: 3000
  },
  build: {
    outDir: "build",
    sourcemap: "hidden"
  },
  resolve: {
    alias: {
      ...CUSTOM_ALIASES,
      ...PROBLEMATIC_LIBRARIES,
      ...POLYFILLS
    }
  }
});
```

We are importing the Worker this way:

```
import * as Comlink from "comlink";

const worker = new ComlinkWorker(new URL("./worker", import.meta.url));
```

If this info is not enough I can try to reproduce it with a blank project.

_Originally posted by @vibaiher-qatium in https://github.com/mathe42/vite-plugin-comlink/issues/52#issuecomment-1119383917_

**Comment by mathe42** [comment]
@vibaiher-qatium created a new issue for this

**Comment by mathe42** [comment]
This is not a problem of this plugin.

See https://github.com/mathe42/test-worker

And as the sourcemap comment (`//# sourceMappingURL=worker.aab1c906.js.map`) points to the correct file this should not be a problem...

**Comment by mathe42** [comment]
@vibaiher-qatium I close this for now feel free to comment or create a new issue if you have problems...

**Comment by vibaiher-qatium** [comment]
@mathe42 The problem with different hashes is when you use the option "hidden" of sourcemap, since the only way to link the sourcemap is using the hash.

As a workaround, we can set the option just to "true", but we decided to use "hidden" since we were not uploading the sourcemaps to the server, we just upload them to an error tracking system to have a better error stack trace.

**Comment by mathe42** [comment]
Than you should create an issue in the Vite repo as this is a Vite problem

**Comment by vibaiher-qatium** [comment]
Thank you!

**Comment by vibaiher-qatium** [comment]
https://github.com/vitejs/vite/issues/8089
