### ISSUE TITLE
Function to terminate worker

### ISSUE THREAD

**Issue by Mexican-Man** [mathe42/vite-plugin-comlink#68]
I know the regular syntax is `Worker.prototype.terminate()`, but I don't see anything like that for `ComlinkWorker`. Is there a way to terminate a `ComlinkWorker`?

**Comment by mathe42** [comment]
Just use
```ts
import {releaseProxy} from 'comlink'

comlink[releaseProxy]()
```
and lose all refrences to that worker. The GarbageCollector should terminate the workers on its own.

**Comment by Mexican-Man** [comment]
Ah good to know.

**Comment by mathe42** [comment]
There is a PR for comlink that removes the need to call that function using weakrefs
