### ISSUE TITLE
ComlinkWorker  使用时不需要导入的嘛

### ISSUE THREAD

**Issue by itmanyong** [mathe42/vite-plugin-comlink#71]
按照说明配置完成无法正常运行,浏览器报错如下，ComlinkWorker这类api从何处导入呢
![image](https://user-images.githubusercontent.com/53500371/178156809-78bf089f-6779-4451-bd5b-6142244517fa.png)

**Comment by mathe42** [comment]
ComlinkWorker is a compile-time helper.

Please provide a füll reproduction! I would guess there is Something wrong with your config

**Comment by itmanyong** [comment]
@mathe42 复现示例 [示例](https://github.com/itmanyong/vite-plugin-comlink-sample01)

**Comment by mathe42** [comment]
Sorry the link doesn't work for me...

**Comment by itmanyong** [comment]
@mathe42 Sorry, I forgot to change it to public.[已经可以访问了](https://github.com/itmanyong/vite-plugin-comlink-sample01)

**Comment by mathe42** [comment]
Make 2 changes:
1. at https://github.com/itmanyong/vite-plugin-comlink-sample01/blob/main/.config/plugins.js#L9 put comlink-plugin first.
2. at https://github.com/itmanyong/vite-plugin-comlink-sample01/blob/main/src/components/CountJsx.jsx#L27 the file is ./worker.js but it is actualy named ./woker.js

I add for the first one a information in the readme.

**Comment by mathe42** [comment]
I close this for now. Feel free to tell me if you got any other problems
