### ISSUE TITLE
install problems -> new ComlinkWorker "not found"

### ISSUE THREAD

**Issue by pcace** [mathe42/vite-plugin-comlink#78]
HI there, i am trying to get vite-plugin-comlink to run, but cannot find the problem why it would not work: 

i have followed the install readme so my vite.config.ts looks like that: 

```
import react from '@vitejs/plugin-react'
import { defineConfig } from 'vite'
import { comlink } from 'vite-plugin-comlink'
import EnvironmentPlugin from 'vite-plugin-environment'

// https://vitejs.dev/config/
export default ({ mode }) => {
  console.error('vite mode', mode)
  return defineConfig({
    envPrefix: 'REACT_APP_',
    logLevel: 'info',
    esbuild: {
      pure: ['console.log', 'console.time', 'console.timeEnd', 'console.warn'],
      minify: ['production', 'preview'].includes(mode),
    },
    plugins: [
      comlink(), // must be the first plugin...
      react(),
      EnvironmentPlugin('all', { prefix: 'REACT_APP_' }),
      EnvironmentPlugin({ PUBLIC_URL: '' }),
    ],
    worker: {
      plugins: [comlink()],
    },
  })
}
```
vite-env.d.ts looks like this: 
```
/// <reference types="vite/client" />
/// <reference types="vite-plugin-comlink/client" />
```

vite-plugin-comlink is installed via `yarn add vite-plugin-comlink` (3.0.4).

the Problem is, when i try to create a new ComlinkWorker like so: 

`const instance = new ComlinkWorker(new URL('./worker.js', import.meta.url)` i get any
`Cannot find name 'ComlinkWorker'.ts(2304)`

Where did i do something wrong? what can be  the Problem? 

Any help would be awesome! 
Thanks a lot!

**Comment by pcace** [comment]
never mind... the vite-env.d.ts was in the wrong place.

**Comment by alii13** [comment]
I am getting the same error where should vite-env.d.ts should be at?

**Comment by mathe42** [comment]
Important is that `vite-plugin-comlink/client` is used by typescript.

That can be done by
```ts
/// <reference types="vite-plugin-comlink/client" />
```

In the `vite-env.d.ts` file if generated or by adding it to tsconfig.
