### ISSUE TITLE
Failed to resolve import 

### ISSUE THREAD

**Issue by pcace** [mathe42/vite-plugin-comlink#79]
Hi there, 
i dont quite know if its an issue with the `vite-plugin-comlink` or if its something on my side.. maybe you have an idea to solve it: 
i have a worker: `clipperWorker.ts` with this content: 
```ts
import { clipper } from './clipper'
export const union = clipper.union
```
and try access it via: 

```ts
const clipperWorker = new ComlinkWorker<typeof import('...[deleted].../src/helpers/clipperWorker')>(
  new URL('...[deleted].../src/helpers/clipperWorker.ts', import.meta.url)

const fromWorker = clipperWorker.union(xyz)
```

resulting in this errormessage from vite:

```
[plugin:vite:import-analysis] Failed to resolve import "C:/...[deleted].../src/helpers/clipperWorker.ts?type=module&worker_url_file" from "...[deleted]...\internal:comlink:appname\src\helpers\clipperWorker.ts?type=module&worker_url_file". Does the file exist?
C:/...[deleted].../src/feature/scenario/SVGfromMesh/internal:comlink:AppName/src/helpers/clipperWorker.ts:5:22
1  |  import '/@vite/env'
2  |  import { expose } from "comlink";
3  |  import * as api from "C:/...[deleted].../src/helpers/clipperWorker.ts?type=module&worker_url_file";
   |                        ^
4  |  expose(api);
5  |
```

this last line looks weird to me : `clipperWorker.ts?type=module&worker_url_file` is that correct? or does it try to get the import from a wrong place?

thanks a lot, 

cheers

**Comment by mathe42** [comment]
Assuming `...[deleted]...` is the same in all places that looks fine to me. Also the `?type=...` is ok.

In 2. code block I would use relative path maybe that fixes it...
Anjd there is a ) missing I would guess that this is only a typo in the issue not actualy in your code...

**Comment by pcace** [comment]
Hi, this seems to do the trick!

its somehow strange to me that imports are different with vite.
```
type ClipperType = typeof import('../../../../../asdf/src/helpers/clipperWorker')
const clipperWorker = new ComlinkWorker<ClipperType>(
  new URL('../../../../../asdf/src/helpers/clipperWorker.ts', import.meta.url)
  // ,
  // {
  //   replacement: 'Worker',
  // }
)
```
the error is gone, but it never actually fires up the worker, i only get a Promise back wich never gets fulfilled: 

this is the worker: 
```
export const add = (a: number, b: number) => {
  console.log('inside worker')
  return a + b
}

```
and this how i fire it up: 
```
    const test = await clipperWorker.add(1, 2)
    console.log('clipperworker', test)
```
non of the console.logs are shown, so i guess its still not correctly imported :/

Cheers

**Comment by mathe42** [comment]
Could you share a full reproduction? Than I can better debug that...
