### ISSUE TITLE
Broken sourcemap when not transforming from original source

### ISSUE THREAD

**Issue by juanevp** [mathe42/vite-plugin-comlink#81]
The transform() function in the plugin returns the sourcemap generated from magic-string which is based on the source received as parameter. But when that source was previously transformed from another source (eg, is a .js file transpiled from a .ts file), the mapping to the original file is lost and the resulting sourcemap is broken from the overwritten line on.
That original mapping is available to the transform() function through the call this.getCombinedSourcemap().
As magic-string does not support generating the sourcemap starting from a previous one, then you would have to merge both sourcemaps using something like what is explained [here](https://stackoverflow.com/a/68974697).

**Comment by mathe42** [comment]
Thanks was not aware of that. If you create a PR this would be fixed more quickly as I currently have no time to implement it...

**Comment by mathe42** [comment]
@juanevp maybe fixed in #84 but don't expect it to be merged in the next 2 weeks.

**Comment by mathe42** [comment]
fixed with 4.0
