### ISSUE TITLE
ReferenceError: ComlinkWorker is not defined

### ISSUE THREAD

**Issue by AdelNorberg** [mathe42/vite-plugin-comlink#91]
Hello! Thanks for the plugin, but I'm having little problems, I'm confused. For some reason I don't have this global variable

Here is a reproduction of the error:
https://codesandbox.io/s/reverent-gould-joqelp?file=/src/main.js

Maybe I'm doing something wrong, but I sat in an attempt to understand what was going on for a long time, but I could not

**Comment by mathe42** [comment]
Yes that is expected! There is no class ComlinkWorker it is transformed to a Worker call at build time so at runtime no ComlinkWorker exists.

**Comment by AdelNorberg** [comment]
Sorry, but I still don't seem to understand:(

The example uses the ComlinkWorker class:
![image](https://user-images.githubusercontent.com/24225624/210376707-8d0be329-ca0d-4b9d-8456-6ba180f49e9e.png)
What do I need to use to make this work during development?
When I use the ComlinkWorker class during development and try to call a function, my Promise always hangs forever

**Comment by mathe42** [comment]
The problem is that in your codesandbox `console.log(import.meta.url);` gives me an error. (just replaced your main.js with that one line).

**Comment by mathe42** [comment]
Closing this as there was no response. Feel free to create a new issue.
