### ISSUE TITLE
ComlinkWorker is Proxy, all worker function calls return infinity Promises

### ISSUE THREAD

**Issue by AD2018** [mathe42/vite-plugin-comlink#92]
Issue demostrating:
`const worker = new ComlinkWorker(...)`
`console.log(worker)`gives Proxy:
![image](https://user-images.githubusercontent.com/25452819/213910239-f7762a45-cfad-4954-9300-46352ebd31b4.png)

In that worker I have exported function `init(data){...}`
if i will call this function:
`const result = await worker.init(...)`, 
it will stop there forever. 

If i will remove `await`, and `console.log(result)` it will give me Promise

One more thing - even if i dont have function in worker, i can do next thing: `worker.someFunctionThatDoesntExist()`, it will return same Promise, as it was with existing function `init(data){...}`

Here is my vite.config.ts
![image](https://user-images.githubusercontent.com/25452819/213910417-7eedcf79-db3e-4ffd-87e4-7a33c7ea8313.png)

Here is how i initialize worker:
![image](https://user-images.githubusercontent.com/25452819/213910439-4c7aaed3-56c2-4c30-afa0-9a26b6338dfa.png)

**Comment by mathe42** [comment]
Yes ComlinkWorker IS a proxy generated by comlink... If you call a function not existing in the worker the retunrned promise will never resolve (that is expected!). So what exactly is your problem?

**Comment by AD2018** [comment]
The problem is next:
Here is my code, where I initialize worker and try to call function `test`:
![image](https://user-images.githubusercontent.com/25452819/213986429-29dee332-8ad8-4cb3-9123-e93a45d5b947.png)

Here is my function test in worker:
![image](https://user-images.githubusercontent.com/25452819/213986489-f0b5dade-f2b3-48b6-aad0-eec714ba1336.png)


As you can see on 1st screen, we call function `test` in line 367, code line 368 will not be executed farther, because `this.geomWorker.test(1, 1)` will return infinity Promise
As you can see on 2nd screen, I have exported function `test` in ChunkWorker.js file(my worker)

**Comment by mathe42** [comment]
Could you provie a full reproduction that I just have to `npm i` and `npm dev` or similar? That would make debugging this much simpler!

**Comment by AD2018** [comment]
@mathe42 
I experimented with ComlinkWorker and find some tips for debug, maybe you can understand what is going on and debug it
**1 Problem:** The problem is the same as above. but i find the reason of it. I created file ChunkWorker.js (worker) in the same folder as the file, where i init ComlinkWorker. Changed url of worker(code is the same, just renamed `test` function to `add`)
![image](https://user-images.githubusercontent.com/25452819/219952402-b200e942-dbb6-4689-890c-7535fd1a4a7a.png)

Its worked, all is good. Then i just changed import url to this:
![image](https://user-images.githubusercontent.com/25452819/219952473-c92e3354-c130-4f89-86de-aecc3e24d0b0.png)

It is working too, all is good. Then i changed import url again to this:
![image](https://user-images.githubusercontent.com/25452819/219952495-4b1aa7b5-da3f-42f4-90e1-1eb96623ffb0.png)

For some reasons i got the same problem as i described before(inifinity Promise). I tried to `console.log` all three urls, they are the same, no difference.
Here is screen of folders to understand structure
![image](https://user-images.githubusercontent.com/25452819/219952664-d06abcf6-8fb5-4ec8-8bf4-62fb8bf96d3a.png)

`ChunkManager.ts` is the file where `ComlinkWorker` is inited.
Maybe now its clear for you what is the problem...

**2 Problem:** 
Look at this screen, this code is working good:
![image](https://user-images.githubusercontent.com/25452819/219952778-5bdcf1b5-c7a0-43ef-be6d-4f0f743078af.png)

Lets just init URL as a constant:
![image](https://user-images.githubusercontent.com/25452819/219952798-ff40befc-2df3-475e-b579-ad883d4eea8c.png)

For some reasons i got this error:
![image](https://user-images.githubusercontent.com/25452819/219952814-807f4c1f-3b3c-4a8f-a170-dbcb4a3b81f9.png)

Lets just init string url as a constant:
![image](https://user-images.githubusercontent.com/25452819/219952887-4d5922c7-ca7c-4a79-8292-ec43568515c0.png)

And again i got this error:
![image](https://user-images.githubusercontent.com/25452819/219952906-337221c8-ad68-466b-8772-06537a29c77c.png)

Any ideas why i get this errors?

**Comment by AD2018** [comment]
I have no more time, just moved the file to another directory
