### ISSUE TITLE
Fails when using WASM-based libraries

### ISSUE THREAD

**Issue by AndrewJSchoen** [mathe42/vite-plugin-comlink#93]
I am trying to use this plugin in a vite-based project, where I am running a worker that uses a wasm-based library.  I can successfully use the library with standard imports into the project, but when I attempt to load the library within the web worker, it stalls, even if the library itself isn't used. I have created a [sandbox](https://codesandbox.io/p/sandbox/friendly-sid-whh2js?file=%2Fsrc%2Fworker.js) that shows this behavior. A couple other notes:

- In the worker.js file, the library is being imported. Commenting this out should allow the App.jsx to retrieve the result of the add function and display it (instead of null). 
- The other stuff in App.jsx just confirms that the wasm-based library is indeed functioning within the non-webworker environment. 
- I tried fiddling with the ordering of the various plugins, but couldn't get anything to work with that.

Is this something that is a limitation of the library, or could it be a configuration issue somewhere?
Thanks!

**Comment by mathe42** [comment]
Thanks for reporting. Quick guess: is your lib running the wasm inside a webworker? Than it might be problematic.

Will digg into it later will take some time...

**Comment by AndrewJSchoen** [comment]
Thanks for the reply. It isn't running a webworker as far as I know, but I may be mistaken. The lib itself is generated through [wasm-bindgen](https://github.com/rustwasm/wasm-bindgen) and [wasm-pack](https://github.com/rustwasm/wasm-pack) using their `bundler` target ([link](https://rustwasm.github.io/docs/wasm-bindgen/reference/deployment.html)). I inquired with them about any limitations this may have but so far haven't heard back.

**Comment by mathe42** [comment]
might be fixed with v5 please try it and if it doesn't work reopen this issue.
