### ISSUE TITLE
Create Worker inside Worker

### ISSUE THREAD

**Issue by ironhacker** [mathe42/vite-plugin-comlink#96]
Creating a worker from the main thread works fine.  However, ComlinkWorker is not available inside a worker.  I'm trying to create additional workers from the first ComlinkWorker.

My use case:

1. Create a worker to process a large data stream, compress, hash, etc (single threaded stuff).
2. Create a worker pool to encrypt chunks of data stream from worker 1 in parallel.

Worker 1 allows the main thread to do just UI stuff.  Additional workers spawned from 1 allow parallel encryption.  Data is never returned to the main thread.

Aside: I tried to do this with just comlink, but ran into issues with Typescript, importScripts and libsodium-wrapper.  vite-plugin-comlink is just so much nicer!

**Comment by mathe42** [comment]
Quick guess:

I think worker in worker works only the types are not correct. Could you test it with 3 Javascript files (or with ignored type errors)?


Currently not home so I can't try it for myself.

**Comment by ironhacker** [comment]
I set up a test.  I'm using Quasar with Vite.

- src/pages/TestPage.vue
- src/workers/test.js
- src/workers/test2.js

TestPage.vue

```
<template>
  <q-page padding>                                                      
    <q-btn color="primary" @click="WorkIt">Go</q-btn>
  </q-page>                                                    
</template>

<script setup>                                                       
                                                                                             
async function WorkIt() {                                    
  console.log('going')                                       
  const worker = new ComlinkWorker(new URL('../workers/test.js', import.meta.url))
  console.log('worker', worker)
  const result = await worker.add(2, 3)                                                    
  console.log('result', result)                                                            
}                                                                                                                                                                                       
</script>
```

test.js

```
export async function add(a, b) {                                         
  const worker = new ComlinkWorker(new URL('./test2.js', import.meta.url))
  return await worker.add(a, b)                                  
}
```

test2.js

```
export async function add(a, b) {                                         
  return a + b
}
```
Output:

```
going
worker Proxy {length: 0, name: 'target', prototype: {…}}
worker creating new worker
```
Error:

`Error: Failed to construct 'Worker': Script at 'internal:comlink:./test2.js' cannot be accessed from origin`

I tried every variation of the path I could think of to no avail:  workers/test.js, ../workers/test.js, etc.

**Comment by ironhacker** [comment]
I was able to get this to work using straight comlink with the Vite specific syntax:

```
import MyWorker from './worker?worker'

const worker = new MyWorker()
```
Still would like to get this working with ComlinkWorker, but at least I it works.

**Comment by mathe42** [comment]
Thanks for trying will have a look next week probably a simple fix.

**Comment by mathe42** [comment]
Look like it works now see example folder - feel free to reopen if issue is still valid
