### ISSUE TITLE
Way to transfer transferable objects in the message + way to terminate worker

### ISSUE THREAD

**Issue by AD2018** [mathe42/vite-plugin-comlink#99]
1)Is there any  way to transfer transferable objects in the message? (3rd argument of `worker.postMessage()`, https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage )

I transfer many of big Uint32Arrays, so it will be good to have this feature

2) Is there any way to terminate worker? https://developer.mozilla.org/en-US/docs/Web/API/Worker/terminate

**Comment by mathe42** [comment]
From comlink docs
```ts
const data = new Uint8Array([1, 2, 3, 4, 5]);
await myProxy.someFunction(Comlink.transfer(data, [data.buffer]));
```

with this plugin you have to import `transfer` from `comlink` and myProxy is the ComlinkWorker "instance"

---

Terminate:

currently not. If the ComlinkWorker "instance" is out of scope it gets Garbage Collected and the worker gets terminated
